# Generated by Django 2.2.17 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('x_coordinate', models.SmallIntegerField()),
                ('y_coordinate', models.SmallIntegerField()),
            ],
        ),
    ]
