# Generated by Django 3.1 on 2021-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210309_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
