# Generated by Django 2.2.17 on 2020-12-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('customer_num', models.IntegerField(default=0)),
                ('introduce', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.IntegerField(default=None)),
            ],
        ),
    ]
